sbuf: sbuf.h File Reference
sbuf.h File Reference
#include <stddef.h>
Classes
struct sbuf
a malloc'd string buffer.
Typedefs
typedef struct sbuf sbuf
a malloc'd string buffer.
Functions
int sbuf_is_full (sbuf s)
checks if a buffer is full.
int sbuf_is_empty (sbuf s)
checks if a buffer is empty.
void sbuf_print (sbuf s)
prints the buffer members.
int sbuf_search_char (sbuf s, char c)
search for a char
int sbuf_search_char_all (sbuf s, char c, int **rv, int *rc)
search for all instances of char
int sbuf_search_str (sbuf s, char *search)
search for a substring
int sbuf_search_str_all (sbuf s, char *search, int **rv, int *rc)
search for all occurances of a substring
sbuf new_sbuf_size (char *string, size_t capacity)
allocates a new buffer of a specific size.
sbuf new_sbuf (char *string)
allocates the smallest buffer possible.
sbuf new_dsbuf (char *string)
allocates the smallest buffer possible but adds a dynamically expanding flag.
int sbuf_realloc (sbuf *b, size_t new_capacity)
reallocates an existing buffer, possibly truncating its contents.
void sbuf_free (sbuf *b)
frees a sbuf's internal pointer if it needs to be freed and sets it to NULL.
int sbuf_append_str (sbuf *s, char *string)
appends a string to a sbuf.
int sbuf_append_char (sbuf *s, char c)
append a single char to the end of a buffer.
int sbuf_clear (sbuf *s)
clear a sbuf's contents and reset its length.
sbuf sbuf_copy (sbuf)
mallocs a duplicate sbuf.
int sbuf_shrink (sbuf *s)
shrink a sbuf to the size of its current contents.
char * sbuf_get_str (sbuf s)
returns the internal buffer ptr of a sbuf.
int sbuf_set_str (sbuf *s, char *string)
clear and set the contents of the sbuf.
char sbuf_get_index (sbuf s, size_t i)
get a sbuf element by index within bounds.
int sbuf_set_index (sbuf *s, size_t i, char c)
set a sbuffer element by index within bounds.
Typedef Documentation
sbuf
typedef struct sbuf sbuf
a malloc'd string buffer.
tracks capacity and length of a dynamic ptr.
Function Documentation
new_dsbuf()
sbuf new_dsbuf (char * string)
allocates the smallest buffer possible but adds a dynamically expanding flag.
Parameters
string the data to store in the buffer
Returns
a newly allocated sbuf struct, empty on failure.
Definition at line 219 of file sbuf.c.
References sbuf::dynamic, and new_sbuf_size().
new_sbuf()
sbuf new_sbuf (char * string)
allocates the smallest buffer possible.
note potentially unsafe due to strlen use.
Parameters
string the data to store in the buffer
Returns
a newly allocated sbuf struct, empty on failure.
Definition at line 208 of file sbuf.c.
References new_sbuf_size().
new_sbuf_size()
sbuf new_sbuf_size (char * string, size_t capacity)
allocates a new buffer of a specific size.
note that allocation is actually 1 larger than specified. buf[capacity + 1] is always string terminator to prevent strfunction errors.
Parameters
string the data to store in the buffer
capacity the max length of string the buffer can store
Returns
a newly allocated sbuf struct, empty on failure.
Definition at line 185 of file sbuf.c.
References sbuf::buf, sbuf::capacity, and sbuf::len.
sbuf_append_char()
int sbuf_append_char (sbuf * s, char c)
append a single char to the end of a buffer.
may expand a sbuf marked dynamic.
Parameters
s the sbuf to append to
c the char to append
Returns
an exit code, setting errno on failure
Definition at line 312 of file sbuf.c.
References sbuf::buf, sbuf::dynamic, sbuf::len, sbuf_is_full(), and sbuf_realloc().
sbuf_append_str()
int sbuf_append_str (sbuf * s, char * string)
appends a string to a sbuf.
Parameters
s the sbuf to append to
string the content to append
Returns
an exit code, setting errno on failure
Definition at line 278 of file sbuf.c.
References sbuf::buf, sbuf::capacity, sbuf::dynamic, sbuf::len, and sbuf_realloc().
sbuf_clear()
int sbuf_clear (sbuf * s)
clear a sbuf's contents and reset its length.
Parameters
s the sbuf to clear
Returns
an exit code, setting errno on failure
Definition at line 337 of file sbuf.c.
References sbuf::buf, sbuf::capacity, and sbuf::len.
sbuf_copy()
sbuf sbuf_copy (sbuf s)
mallocs a duplicate sbuf.
Parameters
s the sbuf data to duplicate
Returns
a newly malloc'd sbuf
Definition at line 354 of file sbuf.c.
References sbuf::buf, sbuf::capacity, and new_sbuf_size().
sbuf_free()
void sbuf_free (sbuf * s)
frees a sbuf's internal pointer if it needs to be freed and sets it to NULL.
zeros out .capacity, .len, and unsets .dyanmic. will not double free.
Parameters
s the sbuf to free
Returns
void
Definition at line 257 of file sbuf.c.
References sbuf::buf, sbuf::capacity, sbuf::dynamic, and sbuf::len.
sbuf_get_index()
char sbuf_get_index (sbuf s, size_t i)
get a sbuf element by index within bounds.
Parameters
s sbuf to get data from
i index to access
Returns
the char in s at index i. returns '\0' and sets errno on failure
Definition at line 411 of file sbuf.c.
References sbuf::buf, and sbuf::capacity.
sbuf_get_str()
char* sbuf_get_str (sbuf s)
returns the internal buffer ptr of a sbuf.
Parameters
s the sbuf to get string from
Returns
the char ptr to the sbuf's buffer (not a copy)
Definition at line 383 of file sbuf.c.
References sbuf::buf.
sbuf_is_empty()
int sbuf_is_empty (sbuf s)
checks if a buffer is empty.
Parameters
s the sbuf to check
Returns
a boolean, or a -1 on error and sets errno
Definition at line 41 of file sbuf.c.
References sbuf::buf, and sbuf::len.
sbuf_is_full()
int sbuf_is_full (sbuf s)
checks if a buffer is full.
Parameters
s the sbuf to check
Returns
a boolean, or a -1 on error and sets errno
Definition at line 26 of file sbuf.c.
References sbuf::buf, sbuf::capacity, and sbuf::len.
sbuf_print()
void sbuf_print (sbuf s)
prints the buffer members.
Parameters
s the sbuf to print
Returns
void
Definition at line 162 of file sbuf.c.
References sbuf::buf, sbuf::capacity, and sbuf::len.
sbuf_realloc()
int sbuf_realloc (sbuf * s, size_t new_capacity)
reallocates an existing buffer, possibly truncating its contents.
Parameters
s the sbuf to reallocate
new_capacity the new size to allocate the sbuf to
Returns
an exit code, setting errno on failure.
Definition at line 232 of file sbuf.c.
References sbuf::buf, sbuf::capacity, and sbuf::len.
sbuf_search_char()
int sbuf_search_char (sbuf s, char c)
search for a char
Parameters
s the sbuf to search
c the char to search for
Returns
index where char was found. -1 if error.
Definition at line 57 of file sbuf.c.
References sbuf::buf, and sbuf::len.
sbuf_search_char_all()
int sbuf_search_char_all (sbuf s, char c, int ** rv, int * rc)
search for all instances of char
Parameters
s the sbuf to search
c the char to search for
rv return vector of indices
rc return vector count
Returns
an exit code, 0: found results, 1: no results, 2: memory error
Definition at line 78 of file sbuf.c.
References sbuf::buf, and sbuf::len.
sbuf_search_str()
int sbuf_search_str (sbuf s, char * search)
search for a substring
Parameters
s the sbuf to search
search the substring to search for
Returns
index where substring is located
Definition at line 108 of file sbuf.c.
References sbuf::buf.
sbuf_search_str_all()
int sbuf_search_str_all (sbuf s, char * search, int ** rv, int * rc)
search for all occurances of a substring
Parameters
s the sbuf to search
search the substring to search for
rv return vector of indices
rc return vector count
Returns
an exit code, 0: found results, 1: no results, 2: memory error
Definition at line 129 of file sbuf.c.
References sbuf::buf, and sbuf::len.
sbuf_set_index()
int sbuf_set_index (sbuf * s, size_t i, char c)
set a sbuffer element by index within bounds.
Parameters
s the sbuf ptr to set
i the index to set
c the char to set i to
Returns
an exit code, setting errno on failure
Definition at line 427 of file sbuf.c.
References sbuf::buf, sbuf::capacity, and sbuf::len.
sbuf_set_str()
int sbuf_set_str (sbuf * s, char * string)
clear and set the contents of the sbuf.
Parameters
s the sbuf ptr to clear and set
string the c string to store in s
Returns
an exit code, setting errno on failure
Definition at line 394 of file sbuf.c.
References sbuf::buf, sbuf::capacity, sbuf::len, and sbuf_clear().
sbuf_shrink()
int sbuf_shrink (sbuf * s)
shrink a sbuf to the size of its current contents.
Parameters
s the sbuf ptr to shrink
Returns
an exit code, setting errno on failure
Definition at line 364 of file sbuf.c.
References sbuf::capacity, sbuf::len, and sbuf_realloc().